services:
  - type: web
    name: api
    env: python
    plan: free
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /api/ping

  - type: web
    name: web
    env: python
    plan: free
    rootDir: web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    autoDeploy: true
    envVars:
      - key: BASE_URL
        fromService:
          type: web
          name: api
          property: url
